# Generated by Django 6.0 on 2025-12-06 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ["title"]},
        ),
        migrations.AddField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                choices=[("daily", "Daily"), ("weekly", "Weekly")],
                default="daily",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="max_per_day",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="habit",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
