# Generated by Django 6.0 on 2025-12-08 12:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_options_habit_frequency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="habit",
            unique_together={("owner", "title")},
        ),
    ]
