# Generated by Django 6.0 on 2025-12-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="is_global",
            field=models.BooleanField(default=False),
        ),
    ]
