# Generated by Django 6.0 on 2025-12-08 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("challenges", "0001_initial"),
        ("participation", "0001_initial"),
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField()),
                ("reason", models.CharField(default="checkin", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checkin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="score_events",
                        to="tracking.checkin",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_events",
                        to="participation.enrollment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaderboardSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField()),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="challenges.challenge",
                    ),
                ),
            ],
            options={
                "unique_together": {("challenge", "period")},
            },
        ),
    ]
