# Generated by Django 6.0 on 2025-12-07 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habits", "0002_alter_habit_options_habit_frequency_and_more"),
        ("participation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("done_at", models.DateField()),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="participation.enrollment",
                    ),
                ),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="habits.habit",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["enrollment", "done_at"],
                        name="tracking_ch_enrollm_2ae1ee_idx",
                    )
                ],
                "unique_together": {("enrollment", "habit", "done_at")},
            },
        ),
    ]
